name: Windows DLL Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build DLL (Release)
        run: |
          msbuild controller_injector/controller_dll/controller_dll.vcxproj /p:Configuration=Release
      - name: Upload DLL Artifact
        uses: actions/upload-artifact@v4
        with:
          name: controller_dll
          path: controller_injector/controller_dll/Release/controller_dll.dll
